/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorInicio;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author HP
 */
public class Inicio extends javax.swing.JFrame {
   
    /**
     * Creates new form Inicio
     */

    
    private static boolean archivoParaLeer;
    private static String  seleccion;
    private static boolean bool;
    private static ArrayList <String> archivos = new ArrayList<>();
    private static int recuperados, susceptibles, expuestos, infectados, semanas;
    public Inicio() {
        initComponents();
        this.setLocation(500, 150);
        // ControladorInicio ctrl = new ControladorInicio();
        
  
        PanelGrafica.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        InfoModelo = new button.MyButton();
        Comparativa = new button.MyButton();
        MunicipiosyLocalidades = new button.MyButton();
        TablasComparativa = new button.MyButton();
        MasInfo1 = new button.MyButton();
        Comparativa1 = new button.MyButton();
        botonSusceptibles = new button.MyButton();
        botonInfectados = new button.MyButton();
        botonRecuperados = new button.MyButton();
        botonExpuestos = new button.MyButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        PanelGrafica = new javax.swing.JPanel();
        botonReset = new button.MyButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        obtenerSusceptibles = new javax.swing.JTextField();
        obtenerRecuperados = new javax.swing.JTextField();
        obtenerExpuestos = new javax.swing.JTextField();
        obtenerInfectados = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        obtenerSemanas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(200, 214, 191));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Cooper Black", 0, 42)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COVID-19");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        InfoModelo.setForeground(new java.awt.Color(255, 255, 255));
        InfoModelo.setText("Información sobre el modelo");
        InfoModelo.setBorderColor(new java.awt.Color(0, 0, 0));
        InfoModelo.setColor(new java.awt.Color(152, 204, 198));
        InfoModelo.setColorClick(new java.awt.Color(152, 204, 198));
        InfoModelo.setColorOver(new java.awt.Color(108, 189, 181));
        InfoModelo.setFocusTraversalPolicyProvider(true);
        InfoModelo.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        InfoModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        InfoModelo.setRadius(50);
        InfoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoModeloActionPerformed(evt);
            }
        });

        Comparativa.setForeground(new java.awt.Color(255, 255, 255));
        Comparativa.setText("Comparativa");
        Comparativa.setBorderColor(new java.awt.Color(26, 31, 30));
        Comparativa.setColor(new java.awt.Color(152, 204, 198));
        Comparativa.setColorClick(new java.awt.Color(152, 204, 198));
        Comparativa.setColorOver(new java.awt.Color(108, 189, 181));
        Comparativa.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        Comparativa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Comparativa.setRadius(50);
        Comparativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComparativaActionPerformed(evt);
            }
        });

        MunicipiosyLocalidades.setForeground(new java.awt.Color(255, 255, 255));
        MunicipiosyLocalidades.setText("Municipios y Localidades");
        MunicipiosyLocalidades.setBorderColor(new java.awt.Color(26, 31, 30));
        MunicipiosyLocalidades.setColor(new java.awt.Color(152, 204, 198));
        MunicipiosyLocalidades.setColorClick(new java.awt.Color(152, 204, 198));
        MunicipiosyLocalidades.setColorOver(new java.awt.Color(108, 189, 181));
        MunicipiosyLocalidades.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        MunicipiosyLocalidades.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MunicipiosyLocalidades.setRadius(50);
        MunicipiosyLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipiosyLocalidadesActionPerformed(evt);
            }
        });

        TablasComparativa.setForeground(new java.awt.Color(255, 255, 255));
        TablasComparativa.setText("Tablas de Comparativa");
        TablasComparativa.setBorderColor(new java.awt.Color(26, 31, 30));
        TablasComparativa.setColor(new java.awt.Color(152, 204, 198));
        TablasComparativa.setColorClick(new java.awt.Color(152, 204, 198));
        TablasComparativa.setColorOver(new java.awt.Color(108, 189, 181));
        TablasComparativa.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        TablasComparativa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TablasComparativa.setRadius(50);
        TablasComparativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablasComparativaActionPerformed(evt);
            }
        });

        MasInfo1.setForeground(new java.awt.Color(255, 255, 255));
        MasInfo1.setText("Más información");
        MasInfo1.setBorderColor(new java.awt.Color(26, 31, 30));
        MasInfo1.setColor(new java.awt.Color(152, 204, 198));
        MasInfo1.setColorClick(new java.awt.Color(152, 204, 198));
        MasInfo1.setColorOver(new java.awt.Color(108, 189, 181));
        MasInfo1.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        MasInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MasInfo1.setRadius(50);
        MasInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasInfo1ActionPerformed(evt);
            }
        });

        Comparativa1.setForeground(new java.awt.Color(255, 255, 255));
        Comparativa1.setText("INTRODUCIR CSV");
        Comparativa1.setBorderColor(new java.awt.Color(26, 31, 30));
        Comparativa1.setColor(new java.awt.Color(152, 204, 198));
        Comparativa1.setColorClick(new java.awt.Color(152, 204, 198));
        Comparativa1.setColorOver(new java.awt.Color(108, 189, 181));
        Comparativa1.setFont(new java.awt.Font("Bodoni MT Condensed", 0, 24)); // NOI18N
        Comparativa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Comparativa1.setRadius(50);
        Comparativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comparativa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Comparativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MunicipiosyLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MasInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TablasComparativa, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comparativa, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addGap(101, 101, 101)
                .addComponent(InfoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Comparativa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TablasComparativa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MunicipiosyLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MasInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Comparativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonSusceptibles.setText("SUCEPTIBLES");
        botonSusceptibles.setBorderColor(new java.awt.Color(108, 189, 181));
        botonSusceptibles.setColor(new java.awt.Color(108, 189, 181));
        botonSusceptibles.setColorClick(new java.awt.Color(108, 189, 181));
        botonSusceptibles.setColorOver(new java.awt.Color(0, 153, 153));
        botonSusceptibles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSusceptibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSusceptiblesActionPerformed(evt);
            }
        });

        botonInfectados.setText("INFECTADOS");
        botonInfectados.setBorderColor(new java.awt.Color(108, 189, 181));
        botonInfectados.setColor(new java.awt.Color(108, 189, 181));
        botonInfectados.setColorClick(new java.awt.Color(108, 189, 181));
        botonInfectados.setColorOver(new java.awt.Color(0, 153, 153));
        botonInfectados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonInfectados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfectadosActionPerformed(evt);
            }
        });

        botonRecuperados.setText("RECUPERADOS");
        botonRecuperados.setBorderColor(new java.awt.Color(108, 189, 181));
        botonRecuperados.setColor(new java.awt.Color(108, 189, 181));
        botonRecuperados.setColorClick(new java.awt.Color(108, 189, 181));
        botonRecuperados.setColorOver(new java.awt.Color(0, 153, 153));
        botonRecuperados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonRecuperados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecuperadosActionPerformed(evt);
            }
        });

        botonExpuestos.setText("EXPUESTOS");
        botonExpuestos.setBorderColor(new java.awt.Color(108, 189, 181));
        botonExpuestos.setColor(new java.awt.Color(108, 189, 181));
        botonExpuestos.setColorClick(new java.awt.Color(108, 189, 181));
        botonExpuestos.setColorOver(new java.awt.Color(0, 153, 153));
        botonExpuestos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonExpuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExpuestosActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(227, 223, 186));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(227, 223, 186));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(227, 223, 186));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(227, 223, 186));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("29 DE NOVIEMBRE DEL 2024");

        PanelGrafica.setBackground(new java.awt.Color(227, 223, 186));

        javax.swing.GroupLayout PanelGraficaLayout = new javax.swing.GroupLayout(PanelGrafica);
        PanelGrafica.setLayout(PanelGraficaLayout);
        PanelGraficaLayout.setHorizontalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        PanelGraficaLayout.setVerticalGroup(
            PanelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        botonReset.setText("RESET");
        botonReset.setBorderColor(new java.awt.Color(108, 189, 181));
        botonReset.setColor(new java.awt.Color(108, 189, 181));
        botonReset.setColorClick(new java.awt.Color(108, 189, 181));
        botonReset.setColorOver(new java.awt.Color(0, 153, 153));
        botonReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(227, 223, 186));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("SUSCEPTIBLES:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("EXPUESTOS:");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("INFECTADOS:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("RECUPERADOS:");

        jLabel2.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel2.setText("INTRODUZCA LOS DATOS A MODELAR");

        obtenerSusceptibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerSusceptiblesActionPerformed(evt);
            }
        });

        obtenerExpuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtenerExpuestosActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(169, 201, 231));
        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("SEMANAS:");

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Archivos disponibles para graficar en base al modelo:");

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel3.setText("SIMULACIÓN DEL COVID_19");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonExpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonRecuperados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonSusceptibles, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonInfectados, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 743, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(375, 375, 375)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(obtenerRecuperados, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(obtenerExpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(obtenerSusceptibles, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(obtenerInfectados, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(109, 109, 109)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(obtenerSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2))))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSusceptibles, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonInfectados, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRecuperados, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonExpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obtenerSusceptibles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obtenerExpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obtenerInfectados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(obtenerRecuperados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(obtenerSemanas)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoModeloActionPerformed
        // TODO add your handling code here:
        
        ControladorInicio ctrl = new ControladorInicio();
        ctrl.infoModelo();
        this.dispose();
        
        
    }//GEN-LAST:event_InfoModeloActionPerformed

    private void botonSusceptiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSusceptiblesActionPerformed
          ControladorInicio.mostrarUnaLinea(0);
    }//GEN-LAST:event_botonSusceptiblesActionPerformed

    private void ComparativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComparativaActionPerformed
        // TODO add your handling code here:
        ControladorInicio ctrl = new ControladorInicio();
        seleccion = choice1.getSelectedItem();
        
        if (bool){
             double[] valores = {susceptibles, expuestos, infectados, recuperados};
            ctrl.comparar(seleccion, valores, semanas);
        }
        else
        ctrl.comparar(seleccion);
        
        this.dispose();
    }//GEN-LAST:event_ComparativaActionPerformed

    private void MunicipiosyLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipiosyLocalidadesActionPerformed
        // TODO add your handling code here:
        ControladorInicio ctrl = new ControladorInicio();
        this.setVisible(false);
        ctrl.munLoc();
        
    }//GEN-LAST:event_MunicipiosyLocalidadesActionPerformed

    private void TablasComparativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablasComparativaActionPerformed
        // TODO add your handling code here:
        ControladorInicio ctrl = new ControladorInicio();
        ctrl.tablac();
        this.dispose();
        
    }//GEN-LAST:event_TablasComparativaActionPerformed

    private void botonInfectadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfectadosActionPerformed
        // TODO add your handling code here:
         ControladorInicio.mostrarUnaLinea(2);
    }//GEN-LAST:event_botonInfectadosActionPerformed

    private void botonRecuperadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecuperadosActionPerformed
        // TODO add your handling code here:
         ControladorInicio.mostrarUnaLinea(3);
        
    }//GEN-LAST:event_botonRecuperadosActionPerformed

    private void botonExpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExpuestosActionPerformed
        // TODO add your handling code here:
         ControladorInicio.mostrarUnaLinea(1);
    }//GEN-LAST:event_botonExpuestosActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        // TODO add your handling code here:
         ControladorInicio.revelarTodo();
    }//GEN-LAST:event_botonResetActionPerformed

    private void MasInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasInfo1ActionPerformed
        // TODO add your handling code here:
        ControladorInicio ctrl = new ControladorInicio();
        ctrl.masIn();
        this.dispose();
    }//GEN-LAST:event_MasInfo1ActionPerformed

    private void Comparativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comparativa1ActionPerformed
        // TODO add your handling code here:
        ControladorInicio ctrl = new ControladorInicio();
        ctrl.ingCsv();
        this.dispose();
    }//GEN-LAST:event_Comparativa1ActionPerformed

    private void obtenerSusceptiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerSusceptiblesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_obtenerSusceptiblesActionPerformed

    private void obtenerExpuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obtenerExpuestosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obtenerExpuestosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ControladorInicio ctrl = new ControladorInicio();
         JTextField[] arr = {obtenerExpuestos, obtenerInfectados, obtenerRecuperados, obtenerSemanas, obtenerSusceptibles};
         bool= ctrl.validarCamposEnteros(arr);
         
         if (bool){
            susceptibles = Integer.parseInt(obtenerSusceptibles.getText());
            expuestos = Integer.parseInt(obtenerExpuestos.getText());
            infectados = Integer.parseInt(obtenerInfectados.getText());
            recuperados = Integer.parseInt(obtenerRecuperados.getText());
            semanas = Integer.parseInt(obtenerSemanas.getText());

            double[] valores = {susceptibles, expuestos, infectados, recuperados};
            
            cargarGraficoArreglo(valores, semanas);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        obtenerSusceptibles.setText("");
        obtenerExpuestos.setText("");
        obtenerInfectados.setText("");
        obtenerRecuperados.setText("");
        obtenerSemanas.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println("Se activó el botón");
        
        
        cargarGraficoAlInicio(); 
        bool =  false;
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    
     private void cargarGraficoArreglo(double [] arr, int semanas) {
        try {
            
            ControladorInicio ctrl = new ControladorInicio();
          
            seleccion = choice1.getSelectedItem();
            System.out.println("Este es el archivo seleccionado" + seleccion);
            JPanel grafico = ctrl.cargarGraficoArreglo(seleccion, arr, semanas);
            grafico.setPreferredSize(new Dimension(600, 400));
            jTable2.setModel(ctrl.obtenerModeloTabla(seleccion));
            PanelGrafica.removeAll();
            PanelGrafica.add(grafico);
            PanelGrafica.revalidate();
            PanelGrafica.repaint();    
        } catch (IOException e) {
            e.printStackTrace(); 
        }
    }
    private void cargarGraficoAlInicio() {
        try {
            
            ControladorInicio ctrl = new ControladorInicio();
          
            seleccion = choice1.getSelectedItem();
            System.out.println("Este es el archivo seleccionado" + seleccion);
            JPanel grafico = ctrl.cargarGrafico(seleccion);
            grafico.setPreferredSize(new Dimension(600, 400));
            jTable2.setModel(ctrl.obtenerModeloTabla(seleccion));
            PanelGrafica.removeAll();
            PanelGrafica.add(grafico);
            PanelGrafica.revalidate();
            PanelGrafica.repaint();    
        } catch (IOException e) {
            e.printStackTrace(); 
        }
    }
    
        
   
    
    
    @Override
    public void setVisible(boolean visible) {
        super.setVisible(visible);
         if (visible) {
            if(!bool){
                
                agregaArchivos();
                choice1.select(seleccion);
                cargarGraficoAlInicio();} // Recargar el gráfico al mostrar la ventana
            else{
                double[] valores = {susceptibles, expuestos, infectados, recuperados};
                agregaArchivos();
                choice1.select(seleccion);
                cargarGraficoArreglo( valores, semanas);
            }
        }
    }

    public void agregaArchivos( ){
        ControladorInicio ctrl = new ControladorInicio();
        archivos.clear();
        archivos =ctrl.obtenerArchivos();
        choice1.removeAll();
            for(int  i = 0; i<archivos.size(); i++)
            choice1.add(archivos.get(i));
            System.out.println(archivos.size());
        
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.MyButton Comparativa;
    private button.MyButton Comparativa1;
    private button.MyButton InfoModelo;
    private button.MyButton MasInfo1;
    private button.MyButton MunicipiosyLocalidades;
    private javax.swing.JPanel PanelGrafica;
    private button.MyButton TablasComparativa;
    private button.MyButton botonExpuestos;
    private button.MyButton botonInfectados;
    private button.MyButton botonRecuperados;
    private button.MyButton botonReset;
    private button.MyButton botonSusceptibles;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField obtenerExpuestos;
    private javax.swing.JTextField obtenerInfectados;
    private javax.swing.JTextField obtenerRecuperados;
    private javax.swing.JTextField obtenerSemanas;
    private javax.swing.JTextField obtenerSusceptibles;
    // End of variables declaration//GEN-END:variables

}
